### PR TITLE
blog: add call for participation

### PR DESCRIPTION
**Pull request by jyhi**

### CODE REVIEW

**Comment by ecwu** [comment]
LGTM

*P.S. Better if we prepare a homepage featured carousel. Maybe I can make one tomorrow noon (CST time)*

**Review by TerenceLiu98 — APPROVED** [review]

**Comment by ecwu** [comment]
I come up with something shown in the screenshot (Taken from [Qizheng Wang's share](https://www.youtube.com/watch?v=epNSyRoMfsM&t=4s) :-))

image

The original Picture can be found here: [Original](https://i.loli.net/2021/08/02/sGDMkRKBhTm4tcP.jpg)

**Comment by billzhonggz** [comment]
LGTM.

**Comment by mchobbylong** [comment]
LGTM.

**Comment by TerenceLiu98** [comment]
Maybe add a mail list / use the Google sheet to collect  speakers' information

**Comment by ecwu** [comment]
Just noticed, @lmy441900 enabled `enableJoinUs` in the post config. But the section generated triggers by this setting is for joining the core group of the HCC.

**Comment by jyhi** [comment]
@ecwu Didn’t pay attention to it. There could be some links to related information after the article. Do you fix this or I fix this?

**Comment by ecwu** [comment]
@lmy441900 Go for it.

**Review by ecwu — APPROVED** [review]
LGTM

**Comment by jyhi** [comment]
Merging.

**Pull request merged**
